// Built-in catalog. Used to seed Supabase and as a fallback when the
// database is unreachable, so the shop never renders empty.
// After launch, edit products in the admin page, not here.
export type SeedCategoryId =
  | "phones"
  | "laptops"
  | "tablets"
  | "audio"
  | "gaming"
  | "solar";

export interface SeedCategory {
  id: SeedCategoryId;
  name: string;
  blurb: string;
  image: string;
}

export interface SeedProduct {
  slug: string;
  name: string;
  brand: string;
  category: SeedCategoryId;
  /** NGN */
  price: number;
  tagline: string;
  image: string;
  rating: number;
  /** "New" | "Flagship" | "Best value" | "Editor's pick" */
  badge?: string;
  /** Storage tiers, capacities or sizes, whatever the product is configured by. */
  options: string[];
  colours: string[];
  specs: Record<string, string>;
}

export const seedCategories: SeedCategory[] = [
  {
    id: "phones",
    name: "Phones",
    blurb: "iPhone and Samsung Galaxy, from budget classics to this year's flagships.",
    image: "/images/products/category-phones.jpg",
  },
  {
    id: "laptops",
    name: "Laptops",
    blurb: "MacBook, Dell, HP, Lenovo and ASUS, bench tested before they ship.",
    image: "/images/products/category-laptops.jpg",
  },
  {
    id: "tablets",
    name: "Tablets & Accessories",
    blurb: "iPads, Galaxy Tabs, chargers, cables and cases.",
    image: "/images/products/category-tablets.jpg",
  },
  {
    id: "audio",
    name: "Audio & Wearables",
    blurb: "AirPods, Galaxy Buds, headphones and smartwatches.",
    image: "/images/products/category-audio.jpg",
  },
  {
    id: "gaming",
    name: "Gaming",
    blurb: "Consoles, controllers, headsets and high-refresh monitors.",
    image: "/images/products/category-gaming.jpg",
  },
  {
    id: "solar",
    name: "Solar & Power",
    blurb: "Inverters, panels, lithium batteries and full home installations.",
    image: "/images/products/category-solar.jpg",
  },
];

export const seedProducts: SeedProduct[] = [
  {
    slug: "iphone-11",
    name: "iPhone 11",
    brand: "Apple",
    category: "phones",
    price: 240000,
    tagline: "A13 Bionic. Dual 12MP.",
    image: "/images/products/iphone-11.jpg",
    rating: 4.6,
    options: ["64GB", "128GB"],
    colours: ["Black", "White", "Red", "Purple"],
    specs: {
      "Chip": "A13 Bionic",
      "Display": "6.1\" Liquid Retina",
      "Camera": "Dual 12MP",
      "Battery": "All-day",
      "OS": "iOS",
      "Network": "5G",
    },
  },
  {
    slug: "iphone-11-pro",
    name: "iPhone 11 Pro",
    brand: "Apple",
    category: "phones",
    price: 290000,
    tagline: "A13 Bionic. Triple 12MP.",
    image: "/images/products/iphone-11-pro.jpg",
    rating: 4.8,
    options: ["64GB", "256GB"],
    colours: ["Space Gray", "Midnight Green", "Silver"],
    specs: {
      "Chip": "A13 Bionic",
      "Display": "5.8\" Super Retina XDR",
      "Camera": "Triple 12MP",
      "Battery": "All-day",
      "OS": "iOS",
      "Network": "5G",
    },
  },
  {
    slug: "iphone-11-pro-max",
    name: "iPhone 11 Pro Max",
    brand: "Apple",
    category: "phones",
    price: 335000,
    tagline: "A13 Bionic. Triple 12MP.",
    image: "/images/products/iphone-11-pro-max.jpg",
    rating: 4.8,
    options: ["64GB", "256GB"],
    colours: ["Space Gray", "Midnight Green", "Gold"],
    specs: {
      "Chip": "A13 Bionic",
      "Display": "6.5\" Super Retina XDR",
      "Camera": "Triple 12MP",
      "Battery": "All-day",
      "OS": "iOS",
      "Network": "5G",
    },
  },
  {
    slug: "iphone-12",
    name: "iPhone 12",
    brand: "Apple",
    category: "phones",
    price: 270000,
    tagline: "A14 Bionic. Dual 12MP.",
    image: "/images/products/iphone-12.jpg",
    rating: 4.6,
    options: ["64GB", "128GB", "256GB"],
    colours: ["Black", "Blue", "Green", "Red"],
    specs: {
      "Chip": "A14 Bionic",
      "Display": "6.1\" Super Retina XDR",
      "Camera": "Dual 12MP",
      "Battery": "All-day",
      "OS": "iOS",
      "Network": "5G",
    },
  },
  {
    slug: "iphone-12-pro",
    name: "iPhone 12 Pro",
    brand: "Apple",
    category: "phones",
    price: 380000,
    tagline: "A14 Bionic. Triple 12MP + LiDAR.",
    image: "/images/products/iphone-12-pro.jpg",
    rating: 4.8,
    options: ["128GB", "256GB"],
    colours: ["Pacific Blue", "Graphite", "Gold"],
    specs: {
      "Chip": "A14 Bionic",
      "Display": "6.1\" Super Retina XDR",
      "Camera": "Triple 12MP + LiDAR",
      "Battery": "All-day",
      "OS": "iOS",
      "Network": "5G",
    },
  },
  {
    slug: "iphone-12-pro-max",
    name: "iPhone 12 Pro Max",
    brand: "Apple",
    category: "phones",
    price: 450000,
    tagline: "A14 Bionic. Triple 12MP + LiDAR.",
    image: "/images/products/iphone-12-pro-max.jpg",
    rating: 4.8,
    options: ["128GB", "256GB", "512GB"],
    colours: ["Pacific Blue", "Graphite", "Silver"],
    specs: {
      "Chip": "A14 Bionic",
      "Display": "6.7\" Super Retina XDR",
      "Camera": "Triple 12MP + LiDAR",
      "Battery": "All-day",
      "OS": "iOS",
      "Network": "5G",
    },
  },
  {
    slug: "iphone-13",
    name: "iPhone 13",
    brand: "Apple",
    category: "phones",
    price: 395000,
    tagline: "A15 Bionic. Dual 12MP.",
    image: "/images/products/iphone-13.jpg",
    rating: 4.6,
    options: ["128GB", "256GB"],
    colours: ["Midnight", "Starlight", "Pink", "Blue"],
    specs: {
      "Chip": "A15 Bionic",
      "Display": "6.1\" Super Retina XDR",
      "Camera": "Dual 12MP",
      "Battery": "All-day",
      "OS": "iOS",
      "Network": "5G",
    },
  },
  {
    slug: "iphone-13-pro-max",
    name: "iPhone 13 Pro Max",
    brand: "Apple",
    category: "phones",
    price: 610000,
    tagline: "A15 Bionic. Triple 12MP + LiDAR.",
    image: "/images/products/iphone-13-pro-max.jpg",
    rating: 4.8,
    options: ["128GB", "256GB", "512GB"],
    colours: ["Sierra Blue", "Graphite", "Gold"],
    specs: {
      "Chip": "A15 Bionic",
      "Display": "6.7\" ProMotion XDR",
      "Camera": "Triple 12MP + LiDAR",
      "Battery": "All-day",
      "OS": "iOS",
      "Network": "5G",
    },
  },
  {
    slug: "iphone-14",
    name: "iPhone 14",
    brand: "Apple",
    category: "phones",
    price: 450000,
    tagline: "A15 Bionic. Dual 12MP.",
    image: "/images/products/iphone-14.jpg",
    rating: 4.6,
    options: ["128GB", "256GB"],
    colours: ["Midnight", "Starlight", "Blue", "Purple"],
    specs: {
      "Chip": "A15 Bionic",
      "Display": "6.1\" Super Retina XDR",
      "Camera": "Dual 12MP",
      "Battery": "All-day",
      "OS": "iOS",
      "Network": "5G",
    },
  },
  {
    slug: "iphone-14-pro",
    name: "iPhone 14 Pro",
    brand: "Apple",
    category: "phones",
    price: 620000,
    tagline: "A16 Bionic. 48MP Pro system.",
    image: "/images/products/iphone-14-pro.jpg",
    rating: 4.8,
    options: ["128GB", "256GB", "512GB"],
    colours: ["Deep Purple", "Space Black", "Silver", "Gold"],
    specs: {
      "Chip": "A16 Bionic",
      "Display": "6.1\" ProMotion, Dynamic Island",
      "Camera": "48MP Pro system",
      "Battery": "All-day",
      "OS": "iOS",
      "Network": "5G",
    },
  },
  {
    slug: "iphone-14-pro-max",
    name: "iPhone 14 Pro Max",
    brand: "Apple",
    category: "phones",
    price: 765000,
    tagline: "A16 Bionic. 48MP Pro system.",
    image: "/images/products/iphone-14-pro-max.jpg",
    rating: 4.8,
    options: ["256GB", "512GB", "1TB"],
    colours: ["Deep Purple", "Space Black", "Gold"],
    specs: {
      "Chip": "A16 Bionic",
      "Display": "6.7\" ProMotion, Dynamic Island",
      "Camera": "48MP Pro system",
      "Battery": "All-day",
      "OS": "iOS",
      "Network": "5G",
    },
  },
  {
    slug: "iphone-15",
    name: "iPhone 15",
    brand: "Apple",
    category: "phones",
    price: 610000,
    tagline: "A16 Bionic. 48MP main.",
    image: "/images/products/iphone-15.png",
    rating: 4.6,
    options: ["128GB", "256GB", "512GB"],
    colours: ["Blue", "Pink", "Yellow", "Black"],
    specs: {
      "Chip": "A16 Bionic",
      "Display": "6.1\" Dynamic Island",
      "Camera": "48MP main",
      "Battery": "All-day",
      "OS": "iOS",
      "Network": "5G",
    },
  },
  {
    slug: "iphone-15-pro",
    name: "iPhone 15 Pro",
    brand: "Apple",
    category: "phones",
    price: 770000,
    tagline: "A17 Pro. 48MP Pro + 3x tele.",
    image: "/images/products/iphone-15-pro.jpg",
    rating: 4.8,
    options: ["128GB", "256GB", "512GB"],
    colours: ["Natural Titanium", "Blue Titanium", "White Titanium", "Black Titanium"],
    specs: {
      "Chip": "A17 Pro",
      "Display": "6.1\" ProMotion, Titanium",
      "Camera": "48MP Pro + 3x tele",
      "Battery": "All-day",
      "OS": "iOS",
      "Network": "5G",
    },
  },
  {
    slug: "iphone-15-pro-max",
    name: "iPhone 15 Pro Max",
    brand: "Apple",
    category: "phones",
    price: 900000,
    tagline: "A17 Pro. 48MP Pro + 5x tetraprism.",
    image: "/images/products/iphone-15-pro-max.jpg",
    rating: 4.8,
    options: ["256GB", "512GB", "1TB"],
    colours: ["Natural Titanium", "Blue Titanium", "White Titanium", "Black Titanium"],
    specs: {
      "Chip": "A17 Pro",
      "Display": "6.7\" ProMotion, Titanium",
      "Camera": "48MP Pro + 5x tetraprism",
      "Battery": "All-day",
      "OS": "iOS",
      "Network": "5G",
    },
  },
  {
    slug: "iphone-16",
    name: "iPhone 16",
    brand: "Apple",
    category: "phones",
    price: 970000,
    tagline: "A18. 48MP Fusion.",
    image: "/images/products/iphone-16.jpg",
    rating: 4.6,
    options: ["128GB", "256GB", "512GB"],
    colours: ["Ultramarine", "Teal", "Pink", "Black"],
    specs: {
      "Chip": "A18",
      "Display": "6.1\" Dynamic Island, Camera Control",
      "Camera": "48MP Fusion",
      "Battery": "All-day",
      "OS": "iOS",
      "Network": "5G",
    },
  },
  {
    slug: "iphone-16-plus",
    name: "iPhone 16 Plus",
    brand: "Apple",
    category: "phones",
    price: 880000,
    tagline: "A18. 48MP Fusion.",
    image: "/images/products/iphone-16-plus.jpg",
    rating: 4.6,
    options: ["128GB", "256GB", "512GB"],
    colours: ["Ultramarine", "Teal", "White", "Black"],
    specs: {
      "Chip": "A18",
      "Display": "6.7\" Dynamic Island, Camera Control",
      "Camera": "48MP Fusion",
      "Battery": "All-day",
      "OS": "iOS",
      "Network": "5G",
    },
  },
  {
    slug: "iphone-16-pro",
    name: "iPhone 16 Pro",
    brand: "Apple",
    category: "phones",
    price: 995000,
    tagline: "A18 Pro. 48MP Fusion + 5x tele.",
    image: "/images/products/iphone-16-pro.jpg",
    rating: 4.8,
    options: ["128GB", "256GB", "512GB", "1TB"],
    colours: ["Desert Titanium", "Natural Titanium", "White Titanium", "Black Titanium"],
    specs: {
      "Chip": "A18 Pro",
      "Display": "6.3\" ProMotion, Titanium",
      "Camera": "48MP Fusion + 5x tele",
      "Battery": "All-day",
      "OS": "iOS",
      "Network": "5G",
    },
  },
  {
    slug: "iphone-16-pro-max",
    name: "iPhone 16 Pro Max",
    brand: "Apple",
    category: "phones",
    price: 1200000,
    tagline: "A18 Pro. 48MP Fusion + 5x tele.",
    image: "/images/products/iphone-16-pro-max.jpg",
    rating: 4.8,
    options: ["256GB", "512GB", "1TB"],
    colours: ["Desert Titanium", "Natural Titanium", "White Titanium", "Black Titanium"],
    specs: {
      "Chip": "A18 Pro",
      "Display": "6.9\" ProMotion, Titanium",
      "Camera": "48MP Fusion + 5x tele",
      "Battery": "All-day",
      "OS": "iOS",
      "Network": "5G",
    },
  },
  {
    slug: "iphone-17",
    name: "iPhone 17",
    brand: "Apple",
    category: "phones",
    price: 1140000,
    tagline: "A19. 48MP Dual Fusion.",
    image: "/images/products/iphone-17.jpg",
    rating: 4.6,
    badge: "New",
    options: ["256GB", "512GB"],
    colours: ["Lavender", "Mist Blue", "Sage", "Black"],
    specs: {
      "Chip": "A19",
      "Display": "6.3\" ProMotion 120Hz",
      "Camera": "48MP Dual Fusion",
      "Battery": "All-day",
      "OS": "iOS",
      "Network": "5G",
    },
  },
  {
    slug: "iphone-17-air",
    name: "iPhone 17 Air",
    brand: "Apple",
    category: "phones",
    price: 1180000,
    tagline: "A19 Pro. 48MP Fusion.",
    image: "/images/products/iphone-17-air.jpg",
    rating: 4.6,
    badge: "New",
    options: ["256GB", "512GB", "1TB"],
    colours: ["Sky Blue", "Cloud White", "Light Gold", "Space Black"],
    specs: {
      "Chip": "A19 Pro",
      "Display": "6.5\" ProMotion, 5.6mm thin",
      "Camera": "48MP Fusion",
      "Battery": "All-day",
      "OS": "iOS",
      "Network": "5G",
    },
  },
  {
    slug: "iphone-17-pro",
    name: "iPhone 17 Pro",
    brand: "Apple",
    category: "phones",
    price: 1590000,
    tagline: "A19 Pro. 48MP triple Fusion, 8x tele.",
    image: "/images/products/iphone-17-pro.jpg",
    rating: 4.8,
    badge: "New",
    options: ["256GB", "512GB", "1TB"],
    colours: ["Cosmic Orange", "Deep Blue", "Silver"],
    specs: {
      "Chip": "A19 Pro",
      "Display": "6.3\" ProMotion, Vapour chamber",
      "Camera": "48MP triple Fusion, 8x tele",
      "Battery": "All-day",
      "OS": "iOS",
      "Network": "5G",
    },
  },
  {
    slug: "iphone-17-pro-max",
    name: "iPhone 17 Pro Max",
    brand: "Apple",
    category: "phones",
    price: 1610000,
    tagline: "A19 Pro. 48MP triple Fusion, 8x tele.",
    image: "/images/products/iphone-17-pro-max.jpg",
    rating: 4.8,
    badge: "Flagship",
    options: ["256GB", "512GB", "1TB", "2TB"],
    colours: ["Cosmic Orange", "Deep Blue", "Silver"],
    specs: {
      "Chip": "A19 Pro",
      "Display": "6.9\" ProMotion, Vapour chamber",
      "Camera": "48MP triple Fusion, 8x tele",
      "Battery": "All-day",
      "OS": "iOS",
      "Network": "5G",
    },
  },
  {
    slug: "galaxy-s20",
    name: "Galaxy S20",
    brand: "Samsung",
    category: "phones",
    price: 330000,
    tagline: "Snapdragon 865. Triple 64MP.",
    image: "/images/products/galaxy-s20.jpg",
    rating: 4.5,
    options: ["128GB"],
    colours: ["Cosmic Grey", "Cloud Blue", "Cloud Pink"],
    specs: {
      "Chip": "Snapdragon 865",
      "Display": "6.2\" Dynamic AMOLED 120Hz",
      "Camera": "Triple 64MP",
      "Battery": "5000mAh class",
      "OS": "Android / One UI",
      "Network": "5G",
    },
  },
  {
    slug: "galaxy-s20-plus",
    name: "Galaxy S20 Plus",
    brand: "Samsung",
    category: "phones",
    price: 292000,
    tagline: "Snapdragon 865. Quad 64MP + DepthVision.",
    image: "/images/products/galaxy-s20-plus.jpg",
    rating: 4.5,
    options: ["128GB", "256GB"],
    colours: ["Cosmic Grey", "Cloud Blue", "Cosmic Black"],
    specs: {
      "Chip": "Snapdragon 865",
      "Display": "6.7\" Dynamic AMOLED 120Hz",
      "Camera": "Quad 64MP + DepthVision",
      "Battery": "5000mAh class",
      "OS": "Android / One UI",
      "Network": "5G",
    },
  },
  {
    slug: "galaxy-s20-ultra",
    name: "Galaxy S20 Ultra",
    brand: "Samsung",
    category: "phones",
    price: 325000,
    tagline: "Snapdragon 865. 108MP + 100x Space Zoom.",
    image: "/images/products/galaxy-s20-ultra.jpg",
    rating: 4.7,
    options: ["128GB", "256GB", "512GB"],
    colours: ["Cosmic Grey", "Cosmic Black"],
    specs: {
      "Chip": "Snapdragon 865",
      "Display": "6.9\" Dynamic AMOLED 120Hz",
      "Camera": "108MP + 100x Space Zoom",
      "Battery": "5000mAh class",
      "OS": "Android / One UI",
      "Network": "5G",
    },
  },
  {
    slug: "galaxy-s21",
    name: "Galaxy S21",
    brand: "Samsung",
    category: "phones",
    price: 275000,
    tagline: "Exynos 2100. Triple 64MP.",
    image: "/images/products/galaxy-s21.jpg",
    rating: 4.5,
    options: ["128GB", "256GB"],
    colours: ["Phantom Violet", "Phantom Grey", "Phantom White"],
    specs: {
      "Chip": "Exynos 2100",
      "Display": "6.2\" Dynamic AMOLED 2X",
      "Camera": "Triple 64MP",
      "Battery": "5000mAh class",
      "OS": "Android / One UI",
      "Network": "5G",
    },
  },
  {
    slug: "galaxy-s21-ultra",
    name: "Galaxy S21 Ultra",
    brand: "Samsung",
    category: "phones",
    price: 535000,
    tagline: "Exynos 2100. 108MP + dual tele, S Pen.",
    image: "/images/products/galaxy-s21-ultra.jpg",
    rating: 4.7,
    options: ["128GB", "256GB", "512GB"],
    colours: ["Phantom Black", "Phantom Silver"],
    specs: {
      "Chip": "Exynos 2100",
      "Display": "6.8\" QHD+ 120Hz",
      "Camera": "108MP + dual tele, S Pen",
      "Battery": "5000mAh class",
      "OS": "Android / One UI",
      "Network": "5G",
    },
  },
  {
    slug: "galaxy-s22",
    name: "Galaxy S22",
    brand: "Samsung",
    category: "phones",
    price: 460000,
    tagline: "Snapdragon 8 Gen 1. 50MP triple.",
    image: "/images/products/galaxy-s22.png",
    rating: 4.5,
    options: ["128GB", "256GB"],
    colours: ["Phantom Black", "Cream", "Green", "Lavender"],
    specs: {
      "Chip": "Snapdragon 8 Gen 1",
      "Display": "6.1\" Dynamic AMOLED 2X",
      "Camera": "50MP triple",
      "Battery": "5000mAh class",
      "OS": "Android / One UI",
      "Network": "5G",
    },
  },
  {
    slug: "galaxy-s22-ultra",
    name: "Galaxy S22 Ultra",
    brand: "Samsung",
    category: "phones",
    price: 735000,
    tagline: "Snapdragon 8 Gen 1. 108MP + built-in S Pen.",
    image: "/images/products/galaxy-s22-ultra.jpg",
    rating: 4.7,
    options: ["128GB", "256GB", "512GB"],
    colours: ["Phantom Black", "Burgundy", "Green"],
    specs: {
      "Chip": "Snapdragon 8 Gen 1",
      "Display": "6.8\" QHD+ Edge",
      "Camera": "108MP + built-in S Pen",
      "Battery": "5000mAh class",
      "OS": "Android / One UI",
      "Network": "5G",
    },
  },
  {
    slug: "galaxy-s23",
    name: "Galaxy S23",
    brand: "Samsung",
    category: "phones",
    price: 570000,
    tagline: "Snapdragon 8 Gen 2. 50MP triple.",
    image: "/images/products/galaxy-s23.jpg",
    rating: 4.5,
    options: ["128GB", "256GB"],
    colours: ["Phantom Black", "Cream", "Green", "Lavender"],
    specs: {
      "Chip": "Snapdragon 8 Gen 2",
      "Display": "6.1\" Dynamic AMOLED 2X",
      "Camera": "50MP triple",
      "Battery": "5000mAh class",
      "OS": "Android / One UI",
      "Network": "5G",
    },
  },
  {
    slug: "galaxy-s23-ultra",
    name: "Galaxy S23 Ultra",
    brand: "Samsung",
    category: "phones",
    price: 680000,
    tagline: "Snapdragon 8 Gen 2. 200MP + S Pen.",
    image: "/images/products/galaxy-s23-ultra.png",
    rating: 4.7,
    options: ["256GB", "512GB", "1TB"],
    colours: ["Phantom Black", "Cream", "Green", "Lavender"],
    specs: {
      "Chip": "Snapdragon 8 Gen 2",
      "Display": "6.8\" QHD+ 120Hz",
      "Camera": "200MP + S Pen",
      "Battery": "5000mAh class",
      "OS": "Android / One UI",
      "Network": "5G",
    },
  },
  {
    slug: "galaxy-s24",
    name: "Galaxy S24",
    brand: "Samsung",
    category: "phones",
    price: 520000,
    tagline: "Snapdragon 8 Gen 3. 50MP + Galaxy AI.",
    image: "/images/products/galaxy-s24.jpg",
    rating: 4.5,
    options: ["128GB", "256GB"],
    colours: ["Onyx Black", "Marble Gray", "Cobalt Violet"],
    specs: {
      "Chip": "Snapdragon 8 Gen 3",
      "Display": "6.2\" Dynamic AMOLED 2X",
      "Camera": "50MP + Galaxy AI",
      "Battery": "5000mAh class",
      "OS": "Android / One UI",
      "Network": "5G",
    },
  },
  {
    slug: "galaxy-s24-plus",
    name: "Galaxy S24 Plus",
    brand: "Samsung",
    category: "phones",
    price: 620000,
    tagline: "Snapdragon 8 Gen 3. 50MP + Galaxy AI.",
    image: "/images/products/galaxy-s24-plus.jpg",
    rating: 4.5,
    options: ["256GB", "512GB"],
    colours: ["Onyx Black", "Marble Gray", "Amber Yellow"],
    specs: {
      "Chip": "Snapdragon 8 Gen 3",
      "Display": "6.7\" QHD+ 120Hz",
      "Camera": "50MP + Galaxy AI",
      "Battery": "5000mAh class",
      "OS": "Android / One UI",
      "Network": "5G",
    },
  },
  {
    slug: "galaxy-s24-ultra",
    name: "Galaxy S24 Ultra",
    brand: "Samsung",
    category: "phones",
    price: 900000,
    tagline: "Snapdragon 8 Gen 3. 200MP + S Pen, Galaxy AI.",
    image: "/images/products/galaxy-s24-ultra.jpg",
    rating: 4.7,
    options: ["256GB", "512GB", "1TB"],
    colours: ["Titanium Black", "Titanium Gray", "Titanium Violet"],
    specs: {
      "Chip": "Snapdragon 8 Gen 3",
      "Display": "6.8\" QHD+ Titanium",
      "Camera": "200MP + S Pen, Galaxy AI",
      "Battery": "5000mAh class",
      "OS": "Android / One UI",
      "Network": "5G",
    },
  },
  {
    slug: "galaxy-s25",
    name: "Galaxy S25",
    brand: "Samsung",
    category: "phones",
    price: 620000,
    tagline: "Snapdragon 8 Elite. 50MP, ProVisual Engine.",
    image: "/images/products/galaxy-s25.jpg",
    rating: 4.5,
    options: ["128GB", "256GB"],
    colours: ["Navy", "Icy Blue", "Mint", "Silver Shadow"],
    specs: {
      "Chip": "Snapdragon 8 Elite",
      "Display": "6.2\" Dynamic AMOLED 2X",
      "Camera": "50MP, ProVisual Engine",
      "Battery": "5000mAh class",
      "OS": "Android / One UI",
      "Network": "5G",
    },
  },
  {
    slug: "galaxy-s25-plus",
    name: "Galaxy S25 Plus",
    brand: "Samsung",
    category: "phones",
    price: 840000,
    tagline: "Snapdragon 8 Elite. 50MP, ProVisual Engine.",
    image: "/images/products/galaxy-s25-plus.jpg",
    rating: 4.5,
    options: ["256GB", "512GB"],
    colours: ["Navy", "Icy Blue", "Mint"],
    specs: {
      "Chip": "Snapdragon 8 Elite",
      "Display": "6.7\" QHD+ 120Hz",
      "Camera": "50MP, ProVisual Engine",
      "Battery": "5000mAh class",
      "OS": "Android / One UI",
      "Network": "5G",
    },
  },
  {
    slug: "galaxy-s25-ultra",
    name: "Galaxy S25 Ultra",
    brand: "Samsung",
    category: "phones",
    price: 1120000,
    tagline: "Snapdragon 8 Elite. 200MP + S Pen.",
    image: "/images/products/galaxy-s25-ultra.jpg",
    rating: 4.7,
    options: ["256GB", "512GB", "1TB"],
    colours: ["Titanium Silverblue", "Titanium Black", "Titanium Whitesilver"],
    specs: {
      "Chip": "Snapdragon 8 Elite",
      "Display": "6.9\" QHD+ Titanium",
      "Camera": "200MP + S Pen",
      "Battery": "5000mAh class",
      "OS": "Android / One UI",
      "Network": "5G",
    },
  },
  {
    slug: "galaxy-s26",
    name: "Galaxy S26",
    brand: "Samsung",
    category: "phones",
    price: 1250000,
    tagline: "Snapdragon 8 Elite Gen 5. 50MP, Galaxy AI 3.",
    image: "/images/products/galaxy-s26.jpg",
    rating: 4.5,
    badge: "New",
    options: ["256GB", "512GB"],
    colours: ["Midnight", "Ice", "Sage"],
    specs: {
      "Chip": "Snapdragon 8 Elite Gen 5",
      "Display": "6.3\" Dynamic AMOLED 2X",
      "Camera": "50MP, Galaxy AI 3",
      "Battery": "5000mAh class",
      "OS": "Android / One UI",
      "Network": "5G",
    },
  },
  {
    slug: "galaxy-s26-plus",
    name: "Galaxy S26 Plus",
    brand: "Samsung",
    category: "phones",
    price: 1460000,
    tagline: "Snapdragon 8 Elite Gen 5. 50MP, Galaxy AI 3.",
    image: "/images/products/galaxy-s26-plus.jpg",
    rating: 4.5,
    badge: "New",
    options: ["256GB", "512GB"],
    colours: ["Midnight", "Ice", "Sage"],
    specs: {
      "Chip": "Snapdragon 8 Elite Gen 5",
      "Display": "6.7\" QHD+ 120Hz",
      "Camera": "50MP, Galaxy AI 3",
      "Battery": "5000mAh class",
      "OS": "Android / One UI",
      "Network": "5G",
    },
  },
  {
    slug: "galaxy-s26-ultra",
    name: "Galaxy S26 Ultra",
    brand: "Samsung",
    category: "phones",
    price: 1680000,
    tagline: "Snapdragon 8 Elite Gen 5. 200MP F1.4 + S Pen.",
    image: "/images/products/galaxy-s26-ultra.png",
    rating: 4.7,
    badge: "Flagship",
    options: ["256GB", "512GB", "1TB"],
    colours: ["Titanium Midnight", "Titanium Ice", "Titanium Sage"],
    specs: {
      "Chip": "Snapdragon 8 Elite Gen 5",
      "Display": "6.9\" anti-reflective QHD+",
      "Camera": "200MP F1.4 + S Pen",
      "Battery": "5000mAh class",
      "OS": "Android / One UI",
      "Network": "5G",
    },
  },
  {
    slug: "macbook-air-13-m4",
    name: "MacBook Air 13\" M4",
    brand: "Apple",
    category: "laptops",
    price: 1220000,
    tagline: "Apple M4. 18h battery.",
    image: "/images/products/macbook-air-13-m4.jpg",
    rating: 4.7,
    options: ["256GB", "512GB", "1TB"],
    colours: ["Midnight", "Starlight", "Sky Blue", "Silver"],
    specs: {
      "Processor": "Apple M4",
      "Display": "13.6\" Liquid Retina",
      "Memory": "18h battery",
      "Ports": "USB-C / Thunderbolt",
      "OS": "macOS",
    },
  },
  {
    slug: "macbook-air-15-m4",
    name: "MacBook Air 15\" M4",
    brand: "Apple",
    category: "laptops",
    price: 1280000,
    tagline: "Apple M4. 18h battery.",
    image: "/images/products/macbook-air-15-m4.jpg",
    rating: 4.7,
    options: ["256GB", "512GB", "1TB"],
    colours: ["Midnight", "Starlight", "Sky Blue", "Silver"],
    specs: {
      "Processor": "Apple M4",
      "Display": "15.3\" Liquid Retina",
      "Memory": "18h battery",
      "Ports": "USB-C / Thunderbolt",
      "OS": "macOS",
    },
  },
  {
    slug: "macbook-pro-14-m4-pro",
    name: "MacBook Pro 14\" M4 Pro",
    brand: "Apple",
    category: "laptops",
    price: 2050000,
    tagline: "Apple M4 Pro. 22h battery.",
    image: "/images/products/macbook-pro-14-m4-pro.jpg",
    rating: 4.7,
    badge: "Editor's pick",
    options: ["512GB", "1TB", "2TB"],
    colours: ["Space Black", "Silver"],
    specs: {
      "Processor": "Apple M4 Pro",
      "Display": "14.2\" Liquid Retina XDR",
      "Memory": "22h battery",
      "Ports": "USB-C / Thunderbolt",
      "OS": "macOS",
    },
  },
  {
    slug: "macbook-pro-16-m4-max",
    name: "MacBook Pro 16\" M4 Max",
    brand: "Apple",
    category: "laptops",
    price: 3450000,
    tagline: "Apple M4 Max. 24h battery.",
    image: "/images/products/macbook-pro-16-m4-max.jpg",
    rating: 4.7,
    options: ["1TB", "2TB", "4TB"],
    colours: ["Space Black", "Silver"],
    specs: {
      "Processor": "Apple M4 Max",
      "Display": "16.2\" Liquid Retina XDR",
      "Memory": "24h battery",
      "Ports": "USB-C / Thunderbolt",
      "OS": "macOS",
    },
  },
  {
    slug: "dell-xps-13",
    name: "Dell XPS 13",
    brand: "Dell",
    category: "laptops",
    price: 1850000,
    tagline: "Intel Core Ultra 7. 16GB RAM.",
    image: "/images/products/dell-xps-13.jpg",
    rating: 4.7,
    options: ["512GB", "1TB"],
    colours: ["Platinum", "Graphite"],
    specs: {
      "Processor": "Intel Core Ultra 7",
      "Display": "13.4\" InfinityEdge OLED",
      "Memory": "16GB RAM",
      "Ports": "USB-C / Thunderbolt",
      "OS": "Windows 11",
    },
  },
  {
    slug: "dell-xps-15",
    name: "Dell XPS 15",
    brand: "Dell",
    category: "laptops",
    price: 2650000,
    tagline: "Intel Core Ultra 9. 32GB RAM, RTX 4060.",
    image: "/images/products/dell-xps-15.jpg",
    rating: 4.7,
    options: ["1TB", "2TB"],
    colours: ["Platinum", "Graphite"],
    specs: {
      "Processor": "Intel Core Ultra 9",
      "Display": "15.6\" OLED 3.5K",
      "Memory": "32GB RAM, RTX 4060",
      "Ports": "USB-C / Thunderbolt",
      "OS": "Windows 11",
    },
  },
  {
    slug: "dell-inspiron-15",
    name: "Dell Inspiron 15",
    brand: "Dell",
    category: "laptops",
    price: 785000,
    tagline: "Intel Core i5-1335U. 16GB RAM.",
    image: "/images/products/dell-inspiron-15.jpg",
    rating: 4.4,
    badge: "Best value",
    options: ["512GB", "1TB"],
    colours: ["Carbon Black", "Platinum Silver"],
    specs: {
      "Processor": "Intel Core i5-1335U",
      "Display": "15.6\" FHD",
      "Memory": "16GB RAM",
      "Ports": "USB-C / Thunderbolt",
      "OS": "Windows 11",
    },
  },
  {
    slug: "dell-latitude-5450",
    name: "Dell Latitude 5450",
    brand: "Dell",
    category: "laptops",
    price: 1380000,
    tagline: "Intel Core Ultra 5. 16GB RAM, vPro.",
    image: "/images/products/dell-latitude-5450.jpg",
    rating: 4.4,
    options: ["512GB", "1TB"],
    colours: ["Titan Grey"],
    specs: {
      "Processor": "Intel Core Ultra 5",
      "Display": "14\" FHD+ business",
      "Memory": "16GB RAM, vPro",
      "Ports": "USB-C / Thunderbolt",
      "OS": "Windows 11",
    },
  },
  {
    slug: "hp-spectre-x360-14",
    name: "HP Spectre x360 14",
    brand: "HP",
    category: "laptops",
    price: 1000000,
    tagline: "Intel Core Ultra 7. Convertible 2-in-1.",
    image: "/images/products/hp-spectre-x360-14.jpg",
    rating: 4.7,
    options: ["512GB", "1TB"],
    colours: ["Nightfall Black", "Slate Blue"],
    specs: {
      "Processor": "Intel Core Ultra 7",
      "Display": "14\" 2.8K OLED touch",
      "Memory": "convertible 2-in-1",
      "Ports": "USB-C / Thunderbolt",
      "OS": "Windows 11",
    },
  },
  {
    slug: "hp-pavilion-15",
    name: "HP Pavilion 15",
    brand: "HP",
    category: "laptops",
    price: 725000,
    tagline: "Intel Core i5-1335U. 16GB RAM.",
    image: "/images/products/hp-pavilion-15.jpg",
    rating: 4.4,
    options: ["512GB"],
    colours: ["Natural Silver", "Fog Blue"],
    specs: {
      "Processor": "Intel Core i5-1335U",
      "Display": "15.6\" FHD IPS",
      "Memory": "16GB RAM",
      "Ports": "USB-C / Thunderbolt",
      "OS": "Windows 11",
    },
  },
  {
    slug: "hp-elitebook-840-g11",
    name: "HP EliteBook 840 G11",
    brand: "HP",
    category: "laptops",
    price: 1480000,
    tagline: "Intel Core Ultra 7. 32GB RAM, vPro.",
    image: "/images/products/hp-elitebook-840-g11.png",
    rating: 4.4,
    options: ["512GB", "1TB"],
    colours: ["Silver"],
    specs: {
      "Processor": "Intel Core Ultra 7",
      "Display": "14\" WUXGA business",
      "Memory": "32GB RAM, vPro",
      "Ports": "USB-C / Thunderbolt",
      "OS": "Windows 11",
    },
  },
  {
    slug: "hp-omen-16",
    name: "HP Omen 16",
    brand: "HP",
    category: "laptops",
    price: 2450000,
    tagline: "AMD Ryzen 9 8945HX. RTX 4070, 32GB.",
    image: "/images/products/hp-omen-16.jpg",
    rating: 4.7,
    options: ["1TB", "2TB"],
    colours: ["Shadow Black"],
    specs: {
      "Processor": "AMD Ryzen 9 8945HX",
      "Display": "16.1\" QHD 240Hz",
      "Memory": "RTX 4070, 32GB",
      "Ports": "USB-C / Thunderbolt",
      "OS": "Windows 11",
    },
  },
  {
    slug: "lenovo-thinkpad-x1-carbon",
    name: "Lenovo ThinkPad X1 Carbon",
    brand: "Lenovo",
    category: "laptops",
    price: 2150000,
    tagline: "Intel Core Ultra 7. Carbon-fibre chassis.",
    image: "/images/products/lenovo-thinkpad-x1-carbon.jpg",
    rating: 4.7,
    options: ["512GB", "1TB"],
    colours: ["Deep Black"],
    specs: {
      "Processor": "Intel Core Ultra 7",
      "Display": "14\" 2.8K OLED",
      "Memory": "carbon-fibre chassis",
      "Ports": "USB-C / Thunderbolt",
      "OS": "Windows 11",
    },
  },
  {
    slug: "lenovo-ideapad-slim-3",
    name: "Lenovo IdeaPad Slim 3",
    brand: "Lenovo",
    category: "laptops",
    price: 625000,
    tagline: "AMD Ryzen 5 7520U. 8GB RAM.",
    image: "/images/products/lenovo-ideapad-slim-3.jpg",
    rating: 4.4,
    options: ["256GB", "512GB"],
    colours: ["Arctic Grey", "Abyss Blue"],
    specs: {
      "Processor": "AMD Ryzen 5 7520U",
      "Display": "15.6\" FHD",
      "Memory": "8GB RAM",
      "Ports": "USB-C / Thunderbolt",
      "OS": "Windows 11",
    },
  },
  {
    slug: "lenovo-legion-5",
    name: "Lenovo Legion 5",
    brand: "Lenovo",
    category: "laptops",
    price: 1880000,
    tagline: "AMD Ryzen 7 8845HS. RTX 4060, 16GB.",
    image: "/images/products/lenovo-legion-5.jpg",
    rating: 4.7,
    options: ["1TB"],
    colours: ["Storm Grey"],
    specs: {
      "Processor": "AMD Ryzen 7 8845HS",
      "Display": "16\" WQXGA 165Hz",
      "Memory": "RTX 4060, 16GB",
      "Ports": "USB-C / Thunderbolt",
      "OS": "Windows 11",
    },
  },
  {
    slug: "asus-rog-zephyrus-g14",
    name: "ASUS ROG Zephyrus G14",
    brand: "Asus",
    category: "laptops",
    price: 2750000,
    tagline: "AMD Ryzen 9 8945HS. RTX 4070, 32GB.",
    image: "/images/products/asus-rog-zephyrus-g14.jpg",
    rating: 4.7,
    options: ["1TB", "2TB"],
    colours: ["Eclipse Gray", "Platinum White"],
    specs: {
      "Processor": "AMD Ryzen 9 8945HS",
      "Display": "14\" OLED 120Hz",
      "Memory": "RTX 4070, 32GB",
      "Ports": "USB-C / Thunderbolt",
      "OS": "Windows 11",
    },
  },
  {
    slug: "asus-vivobook-15",
    name: "ASUS Vivobook 15",
    brand: "Asus",
    category: "laptops",
    price: 685000,
    tagline: "Intel Core i5-1335U. 16GB RAM.",
    image: "/images/products/asus-vivobook-15.jpg",
    rating: 4.4,
    options: ["512GB"],
    colours: ["Indie Black", "Cool Silver"],
    specs: {
      "Processor": "Intel Core i5-1335U",
      "Display": "15.6\" FHD",
      "Memory": "16GB RAM",
      "Ports": "USB-C / Thunderbolt",
      "OS": "Windows 11",
    },
  },
  {
    slug: "ipad-11th-gen",
    name: "iPad (11th gen)",
    brand: "Apple",
    category: "tablets",
    price: 625000,
    tagline: "A16 chip. 10.9\" Liquid Retina.",
    image: "/images/products/ipad-11th-gen.jpg",
    rating: 4.5,
    options: ["128GB", "256GB", "512GB"],
    colours: ["Blue", "Pink", "Yellow", "Silver"],
    specs: {
      "Chip": "A16 chip",
      "Display": "10.9\" Liquid Retina",
      "Warranty": "12 months",
    },
  },
  {
    slug: "ipad-air-13-m3",
    name: "iPad Air 13\" M3",
    brand: "Apple",
    category: "tablets",
    price: 985000,
    tagline: "Apple M3. 13\" Liquid Retina.",
    image: "/images/products/ipad-air-13-m3.jpg",
    rating: 4.5,
    options: ["128GB", "256GB", "512GB"],
    colours: ["Space Gray", "Starlight", "Purple", "Blue"],
    specs: {
      "Chip": "Apple M3",
      "Display": "13\" Liquid Retina",
      "Warranty": "12 months",
    },
  },
  {
    slug: "ipad-pro-13-m4",
    name: "iPad Pro 13\" M4",
    brand: "Apple",
    category: "tablets",
    price: 1720000,
    tagline: "Apple M4. 13\" Ultra Retina XDR OLED.",
    image: "/images/products/ipad-pro-13-m4.jpg",
    rating: 4.5,
    badge: "Editor's pick",
    options: ["256GB", "512GB", "1TB"],
    colours: ["Space Black", "Silver"],
    specs: {
      "Chip": "Apple M4",
      "Display": "13\" Ultra Retina XDR OLED",
      "Warranty": "12 months",
    },
  },
  {
    slug: "galaxy-tab-s10-fe",
    name: "Galaxy Tab S10 FE",
    brand: "Samsung",
    category: "tablets",
    price: 725000,
    tagline: "Exynos 1580. 10.9\" LCD, S Pen included.",
    image: "/images/products/galaxy-tab-s10-fe.png",
    rating: 4.5,
    options: ["128GB", "256GB"],
    colours: ["Gray", "Silver", "Blue"],
    specs: {
      "Chip": "Exynos 1580",
      "Display": "10.9\" LCD, S Pen included",
      "Warranty": "12 months",
    },
  },
  {
    slug: "galaxy-tab-s11-ultra",
    name: "Galaxy Tab S11 Ultra",
    brand: "Samsung",
    category: "tablets",
    price: 1920000,
    tagline: "Dimensity 9400+. 14.6\" Dynamic AMOLED 2X.",
    image: "/images/products/galaxy-tab-s11-ultra.jpg",
    rating: 4.5,
    options: ["256GB", "512GB", "1TB"],
    colours: ["Gray", "Silver"],
    specs: {
      "Chip": "Dimensity 9400+",
      "Display": "14.6\" Dynamic AMOLED 2X",
      "Warranty": "12 months",
    },
  },
  {
    slug: "20w-usb-c-power-adapter",
    name: "20W USB-C Power Adapter",
    brand: "Apple",
    category: "tablets",
    price: 22000,
    tagline: "20W fast charge. USB-C PD.",
    image: "/images/products/20w-usb-c-power-adapter.jpg",
    rating: 4.5,
    options: [],
    colours: ["White"],
    specs: {
      "Output": "20W fast charge",
      "Details": "USB-C PD",
      "Warranty": "12 months",
    },
  },
  {
    slug: "magsafe-charger",
    name: "MagSafe Charger",
    brand: "Apple",
    category: "tablets",
    price: 35000,
    tagline: "15W magnetic. 1m cable.",
    image: "/images/products/magsafe-charger.jpg",
    rating: 4.5,
    options: [],
    colours: ["White"],
    specs: {
      "Output": "15W magnetic",
      "Details": "1m cable",
      "Warranty": "12 months",
    },
  },
  {
    slug: "65w-gan-charger",
    name: "65W GaN Charger",
    brand: "Anker",
    category: "tablets",
    price: 38000,
    tagline: "65W 3-port GaN. USB-C x2 + USB-A.",
    image: "/images/products/65w-gan-charger.jpg",
    rating: 4.5,
    badge: "Best value",
    options: [],
    colours: ["Black", "White"],
    specs: {
      "Output": "65W 3-port GaN",
      "Details": "USB-C x2 + USB-A",
      "Warranty": "12 months",
    },
  },
  {
    slug: "20000mah-power-bank",
    name: "20,000mAh Power Bank",
    brand: "Anker",
    category: "tablets",
    price: 24500,
    tagline: "20000mAh, 30W PD. USB-C in/out.",
    image: "/images/products/20000mah-power-bank.jpg",
    rating: 4.5,
    options: [],
    colours: ["Black"],
    specs: {
      "Output": "20000mAh, 30W PD",
      "Details": "USB-C in/out",
      "Warranty": "12 months",
    },
  },
  {
    slug: "usb-c-to-usb-c-cable-2m",
    name: "USB-C to USB-C Cable (2m)",
    brand: "Anker",
    category: "tablets",
    price: 12000,
    tagline: "240W rated. Braided nylon.",
    image: "/images/products/usb-c-to-usb-c-cable-2m.jpg",
    rating: 4.5,
    options: [],
    colours: ["Black", "White"],
    specs: {
      "Output": "240W rated",
      "Details": "braided nylon",
      "Warranty": "12 months",
    },
  },
  {
    slug: "clear-magsafe-case",
    name: "Clear MagSafe Case",
    brand: "Apple",
    category: "tablets",
    price: 15000,
    tagline: "drop-tested. Magnet array.",
    image: "/images/products/clear-magsafe-case.jpg",
    rating: 4.5,
    options: [],
    colours: ["Clear"],
    specs: {
      "Output": "drop-tested",
      "Details": "magnet array",
      "Warranty": "12 months",
    },
  },
  {
    slug: "airpods-4-anc",
    name: "AirPods 4 (ANC)",
    brand: "Apple",
    category: "audio",
    price: 270000,
    tagline: "Active Noise Cancellation. 30h with case.",
    image: "/images/products/airpods-4-anc.jpg",
    rating: 4.6,
    options: ["Active Noise Cancellation", "Adaptive Audio", "Spatial Audio"],
    colours: ["White"],
    specs: {
      "Type": "Buds",
      "Highlight": "Active Noise Cancellation",
      "Battery": "30h with case",
      "Warranty": "12 months",
    },
  },
  {
    slug: "airpods-pro-3",
    name: "AirPods Pro 3",
    brand: "Apple",
    category: "audio",
    price: 260000,
    tagline: "2x ANC, heart-rate sensing. Live translation.",
    image: "/images/products/airpods-pro-3.jpg",
    rating: 4.6,
    badge: "New",
    options: ["Adaptive ANC", "Heart-rate sensor", "Live Translation"],
    colours: ["White"],
    specs: {
      "Type": "Buds",
      "Highlight": "2x ANC, heart-rate sensing",
      "Battery": "live translation",
      "Warranty": "12 months",
    },
  },
  {
    slug: "airpods-max",
    name: "AirPods Max",
    brand: "Apple",
    category: "audio",
    price: 760000,
    tagline: "over-ear, USB-C. 20h ANC playback.",
    image: "/images/products/airpods-max.jpg",
    rating: 4.6,
    options: ["Computational audio", "Spatial Audio", "20h battery"],
    colours: ["Midnight", "Starlight", "Blue", "Purple"],
    specs: {
      "Type": "Headphones",
      "Highlight": "over-ear, USB-C",
      "Battery": "20h ANC playback",
      "Warranty": "12 months",
    },
  },
  {
    slug: "galaxy-buds3-pro",
    name: "Galaxy Buds3 Pro",
    brand: "Samsung",
    category: "audio",
    price: 295000,
    tagline: "adaptive ANC. Galaxy AI interpreter.",
    image: "/images/products/galaxy-buds3-pro.jpg",
    rating: 4.6,
    options: ["Adaptive ANC", "24-bit Hi-Fi", "Interpreter mode"],
    colours: ["Silver", "White"],
    specs: {
      "Type": "Buds",
      "Highlight": "adaptive ANC",
      "Battery": "Galaxy AI interpreter",
      "Warranty": "12 months",
    },
  },
  {
    slug: "sony-wh-1000xm6",
    name: "Sony WH-1000XM6",
    brand: "Sony",
    category: "audio",
    price: 520000,
    tagline: "industry-leading ANC. 30h battery.",
    image: "/images/products/sony-wh-1000xm6.jpg",
    rating: 4.6,
    badge: "Editor's pick",
    options: ["Adaptive ANC", "LDAC", "30h battery"],
    colours: ["Black", "Platinum Silver"],
    specs: {
      "Type": "Headphones",
      "Highlight": "industry-leading ANC",
      "Battery": "30h battery",
      "Warranty": "12 months",
    },
  },
  {
    slug: "apple-watch-series-10",
    name: "Apple Watch Series 10",
    brand: "Apple",
    category: "audio",
    price: 485000,
    tagline: "wide-angle OLED. Sleep apnea alerts.",
    image: "/images/products/apple-watch-series-10.jpg",
    rating: 4.6,
    options: ["42mm", "46mm"],
    colours: ["Jet Black", "Rose Gold", "Silver"],
    specs: {
      "Type": "Watch",
      "Highlight": "wide-angle OLED",
      "Battery": "sleep apnea alerts",
      "Warranty": "12 months",
    },
  },
  {
    slug: "apple-watch-ultra-2",
    name: "Apple Watch Ultra 2",
    brand: "Apple",
    category: "audio",
    price: 720000,
    tagline: "titanium, 3000 nits. 36h battery, dive-rated.",
    image: "/images/products/apple-watch-ultra-2.jpg",
    rating: 4.6,
    options: ["49mm"],
    colours: ["Natural Titanium", "Black Titanium"],
    specs: {
      "Type": "Watch",
      "Highlight": "titanium, 3000 nits",
      "Battery": "36h battery, dive-rated",
      "Warranty": "12 months",
    },
  },
  {
    slug: "galaxy-watch-7",
    name: "Galaxy Watch 7",
    brand: "Samsung",
    category: "audio",
    price: 325000,
    tagline: "Exynos W1000. BioActive sensor.",
    image: "/images/products/galaxy-watch-7.jpg",
    rating: 4.6,
    options: ["40mm", "44mm"],
    colours: ["Green", "Cream", "Silver"],
    specs: {
      "Type": "Watch",
      "Highlight": "Exynos W1000",
      "Battery": "BioActive sensor",
      "Warranty": "12 months",
    },
  },
  {
    slug: "playstation-5-slim",
    name: "PlayStation 5 Slim",
    brand: "Sony",
    category: "gaming",
    price: 830000,
    tagline: "AMD Zen 2, RDNA 2. 1TB SSD, 4K 120fps.",
    image: "/images/products/playstation-5-slim.jpg",
    rating: 4.7,
    options: ["1TB"],
    colours: ["White"],
    specs: {
      "Platform": "Sony",
      "Hardware": "AMD Zen 2, RDNA 2",
      "Details": "1TB SSD, 4K 120fps",
      "Warranty": "12 months",
    },
  },
  {
    slug: "playstation-5-pro",
    name: "PlayStation 5 Pro",
    brand: "Sony",
    category: "gaming",
    price: 1390000,
    tagline: "enhanced GPU + PSSR. 2TB SSD, ray tracing.",
    image: "/images/products/playstation-5-pro.jpg",
    rating: 4.7,
    badge: "New",
    options: ["2TB"],
    colours: ["White"],
    specs: {
      "Platform": "Sony",
      "Hardware": "enhanced GPU + PSSR",
      "Details": "2TB SSD, ray tracing",
      "Warranty": "12 months",
    },
  },
  {
    slug: "xbox-series-x",
    name: "Xbox Series X",
    brand: "Microsoft",
    category: "gaming",
    price: 445000,
    tagline: "12 TFLOPS RDNA 2. 1TB SSD, 4K 120fps.",
    image: "/images/products/xbox-series-x.jpg",
    rating: 4.7,
    options: ["1TB"],
    colours: ["Black"],
    specs: {
      "Platform": "Microsoft",
      "Hardware": "12 TFLOPS RDNA 2",
      "Details": "1TB SSD, 4K 120fps",
      "Warranty": "12 months",
    },
  },
  {
    slug: "xbox-series-s",
    name: "Xbox Series S",
    brand: "Microsoft",
    category: "gaming",
    price: 425000,
    tagline: "4 TFLOPS RDNA 2. 512GB SSD, 1440p.",
    image: "/images/products/xbox-series-s.png",
    rating: 4.7,
    badge: "Best value",
    options: ["512GB"],
    colours: ["White", "Black"],
    specs: {
      "Platform": "Microsoft",
      "Hardware": "4 TFLOPS RDNA 2",
      "Details": "512GB SSD, 1440p",
      "Warranty": "12 months",
    },
  },
  {
    slug: "dualsense-wireless-controller",
    name: "DualSense Wireless Controller",
    brand: "Sony",
    category: "gaming",
    price: 105000,
    tagline: "haptic feedback. Adaptive triggers.",
    image: "/images/products/dualsense-wireless-controller.jpg",
    rating: 4.7,
    options: [],
    colours: ["White", "Midnight Black", "Cosmic Red"],
    specs: {
      "Platform": "Sony",
      "Hardware": "haptic feedback",
      "Details": "adaptive triggers",
      "Warranty": "12 months",
    },
  },
  {
    slug: "nintendo-switch-2",
    name: "Nintendo Switch 2",
    brand: "Nintendo",
    category: "gaming",
    price: 625000,
    tagline: "custom NVIDIA. 7.9\" 1080p HDR, dock 4K.",
    image: "/images/products/nintendo-switch-2.jpg",
    rating: 4.7,
    options: ["256GB"],
    colours: ["Neon", "Black"],
    specs: {
      "Platform": "Nintendo",
      "Hardware": "custom NVIDIA",
      "Details": "7.9\" 1080p HDR, dock 4K",
      "Warranty": "12 months",
    },
  },
  {
    slug: "pro-gaming-headset-7-1",
    name: "Pro Gaming Headset 7.1",
    brand: "HyperX",
    category: "gaming",
    price: 88000,
    tagline: "7.1 surround. Memory-foam, boom mic.",
    image: "/images/products/pro-gaming-headset-7-1.jpg",
    rating: 4.7,
    options: [],
    colours: ["Black", "Red"],
    specs: {
      "Platform": "HyperX",
      "Hardware": "7.1 surround",
      "Details": "memory-foam, boom mic",
      "Warranty": "12 months",
    },
  },
  {
    slug: "27-qhd-165hz-gaming-monitor",
    name: "27\" QHD 165Hz Gaming Monitor",
    brand: "Asus",
    category: "gaming",
    price: 345000,
    tagline: "1ms IPS, FreeSync. HDMI 2.1 + DisplayPort.",
    image: "/images/products/27-qhd-165hz-gaming-monitor.jpg",
    rating: 4.7,
    options: ["27 inch"],
    colours: ["Black"],
    specs: {
      "Platform": "Asus",
      "Hardware": "1ms IPS, FreeSync",
      "Details": "HDMI 2.1 + DisplayPort",
      "Warranty": "12 months",
    },
  },
  {
    slug: "quantum-hybrid-inverter-3-5kva",
    name: "Quantum Hybrid Inverter 3.5kVA",
    brand: "Culverin",
    category: "solar",
    price: 725000,
    tagline: "3.5kVA / 24V pure sine. 80A MPPT controller.",
    image: "/images/products/quantum-hybrid-inverter-3-5kva.jpg",
    rating: 4.6,
    badge: "Best value",
    options: ["3.5kVA"],
    colours: ["Graphite"],
    specs: {
      "Capacity": "3.5kVA / 24V pure sine",
      "Includes": "80A MPPT controller",
      "Installation": "Available nationwide",
      "Warranty": "24 months",
    },
  },
  {
    slug: "quantum-hybrid-inverter-5kva",
    name: "Quantum Hybrid Inverter 5kVA",
    brand: "Culverin",
    category: "solar",
    price: 1480000,
    tagline: "5kVA / 48V pure sine. 100A MPPT, WiFi monitoring.",
    image: "/images/products/quantum-hybrid-inverter-5kva.jpg",
    rating: 4.6,
    badge: "Editor's pick",
    options: ["5kVA"],
    colours: ["Graphite"],
    specs: {
      "Capacity": "5kVA / 48V pure sine",
      "Includes": "100A MPPT, WiFi monitoring",
      "Installation": "Available nationwide",
      "Warranty": "24 months",
    },
  },
  {
    slug: "quantum-hybrid-inverter-10kva",
    name: "Quantum Hybrid Inverter 10kVA",
    brand: "Culverin",
    category: "solar",
    price: 2850000,
    tagline: "10kVA / 48V three-phase ready. Parallel-capable.",
    image: "/images/products/quantum-hybrid-inverter-10kva.jpg",
    rating: 4.6,
    options: ["10kVA"],
    colours: ["Graphite"],
    specs: {
      "Capacity": "10kVA / 48V three-phase ready",
      "Includes": "parallel-capable",
      "Installation": "Available nationwide",
      "Warranty": "24 months",
    },
  },
  {
    slug: "550w-monocrystalline-panel",
    name: "550W Monocrystalline Panel",
    brand: "Jinko",
    category: "solar",
    price: 170000,
    tagline: "550W half-cut mono. 25-year performance warranty.",
    image: "/images/products/550w-monocrystalline-panel.jpg",
    rating: 4.6,
    options: ["550W"],
    colours: ["Black frame"],
    specs: {
      "Capacity": "550W half-cut mono",
      "Includes": "25-year performance warranty",
      "Installation": "Available nationwide",
      "Warranty": "24 months",
    },
  },
  {
    slug: "220ah-lithium-battery-lifepo4",
    name: "220Ah Lithium Battery (LiFePO4)",
    brand: "Felicity",
    category: "solar",
    price: 985000,
    tagline: "51.2V 220Ah, 11.2kWh. 6000+ cycles, BMS.",
    image: "/images/products/220ah-lithium-battery-lifepo4.jpg",
    rating: 4.6,
    options: ["220Ah"],
    colours: ["Graphite"],
    specs: {
      "Capacity": "51.2V 220Ah, 11.2kWh",
      "Includes": "6000+ cycles, BMS",
      "Installation": "Available nationwide",
      "Warranty": "24 months",
    },
  },
  {
    slug: "6-6kw-rooftop-solar-array",
    name: "6.6kW Rooftop Solar Array",
    brand: "Culverin",
    category: "solar",
    price: 4900000,
    tagline: "12 x 550W panels. Full installation included.",
    image: "/images/products/6-6kw-rooftop-solar-array.jpg",
    rating: 4.6,
    options: ["6.6kW"],
    colours: ["Black frame"],
    specs: {
      "Capacity": "12 x 550W panels",
      "Includes": "full installation included",
      "Installation": "Available nationwide",
      "Warranty": "24 months",
    },
  },
  {
    slug: "home-backup-bundle-5kva",
    name: "Home Backup Bundle 5kVA",
    brand: "Culverin",
    category: "solar",
    price: 2750000,
    tagline: "5kVA inverter + 2 batteries + 6 panels. Turnkey install.",
    image: "/images/products/home-backup-bundle-5kva.jpg",
    rating: 4.6,
    options: ["5kVA bundle"],
    colours: ["Graphite"],
    specs: {
      "Capacity": "5kVA inverter + 2 batteries + 6 panels",
      "Includes": "turnkey install",
      "Installation": "Available nationwide",
      "Warranty": "24 months",
    },
  },
];
