// Generated by scripts/fetch-images.mjs — do not edit by hand.
// Attribution for product photography. Wikimedia images are CC-licensed and
// legally require credit; Unsplash does not require it but asks for it.

export interface ImageCredit {
  slug: string;
  name: string;
  provider: string;
  title: string;
  artist: string;
  licence: string;
  source: string;
}

export const imageCredits: ImageCredit[] = [
  {
    "slug": "iphone-11",
    "name": "iPhone 11",
    "provider": "Wikimedia Commons",
    "title": "Scan of back of iPhone 11 Pro Max Space Grey.jpg",
    "artist": "Dllu",
    "licence": "CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Scan_of_back_of_iPhone_11_Pro_Max_Space_Grey.jpg"
  },
  {
    "slug": "iphone-11-pro",
    "name": "iPhone 11 Pro",
    "provider": "Wikimedia Commons",
    "title": "Scan of back of iPhone 11 Pro Max Space Grey.jpg",
    "artist": "Dllu",
    "licence": "CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Scan_of_back_of_iPhone_11_Pro_Max_Space_Grey.jpg"
  },
  {
    "slug": "iphone-11-pro-max",
    "name": "iPhone 11 Pro Max",
    "provider": "Wikimedia Commons",
    "title": "Scan of back of iPhone 11 Pro Max Space Grey.jpg",
    "artist": "Dllu",
    "licence": "CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Scan_of_back_of_iPhone_11_Pro_Max_Space_Grey.jpg"
  },
  {
    "slug": "iphone-12",
    "name": "iPhone 12",
    "provider": "Wikimedia Commons",
    "title": "IPhone 12 Pro Pacific Blue 256g.jpg",
    "artist": "茅野ふたば",
    "licence": "CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:IPhone_12_Pro_Pacific_Blue_256g.jpg"
  },
  {
    "slug": "iphone-12-pro",
    "name": "iPhone 12 Pro",
    "provider": "Wikimedia Commons",
    "title": "IPhone 12 Pro Max - 3.jpg",
    "artist": "KKPCW",
    "licence": "CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:IPhone_12_Pro_Max_-_3.jpg"
  },
  {
    "slug": "iphone-12-pro-max",
    "name": "iPhone 12 Pro Max",
    "provider": "Wikimedia Commons",
    "title": "IPhone 12 Pro Max - 3.jpg",
    "artist": "KKPCW",
    "licence": "CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:IPhone_12_Pro_Max_-_3.jpg"
  },
  {
    "slug": "iphone-13",
    "name": "iPhone 13",
    "provider": "Wikimedia Commons",
    "title": "Apple iPhone 13 Pro on MacBook Pro 05.jpg",
    "artist": "SimonWaldherr",
    "licence": "CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Apple_iPhone_13_Pro_on_MacBook_Pro_05.jpg"
  },
  {
    "slug": "iphone-13-pro-max",
    "name": "iPhone 13 Pro Max",
    "provider": "Wikimedia Commons",
    "title": "Apple iPhone 13 Pro and 13 Pro Max.jpg",
    "artist": "SimonWaldherr",
    "licence": "CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Apple_iPhone_13_Pro_and_13_Pro_Max.jpg"
  },
  {
    "slug": "iphone-14",
    "name": "iPhone 14",
    "provider": "Wikimedia Commons",
    "title": "IPhone 14 Pro - 3.jpg",
    "artist": "KKPCW（Kyu3）",
    "licence": "CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:IPhone_14_Pro_-_3.jpg"
  },
  {
    "slug": "iphone-14-pro",
    "name": "iPhone 14 Pro",
    "provider": "Wikimedia Commons",
    "title": "IPhone 14 Pro - 3.jpg",
    "artist": "KKPCW（Kyu3）",
    "licence": "CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:IPhone_14_Pro_-_3.jpg"
  },
  {
    "slug": "iphone-14-pro-max",
    "name": "iPhone 14 Pro Max",
    "provider": "Wikimedia Commons",
    "title": "Back of the iPhone 14 Pro Max.jpg",
    "artist": "Hajoon0102",
    "licence": "CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Back_of_the_iPhone_14_Pro_Max.jpg"
  },
  {
    "slug": "iphone-15",
    "name": "iPhone 15",
    "provider": "Wikimedia Commons",
    "title": "IPhone 15 机型价格 & 性能数据对比图.png",
    "artist": "杀破狼 killthewolf.eth",
    "licence": "CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:IPhone_15_%E6%9C%BA%E5%9E%8B%E4%BB%B7%E6%A0%BC_%26_%E6%80%A7%E8%83%BD%E6%95%B0%E6%8D%AE%E5%AF%B9%E6%AF%94%E5%9B%BE.png"
  },
  {
    "slug": "iphone-15-pro",
    "name": "iPhone 15 Pro",
    "provider": "Wikimedia Commons",
    "title": "IPhone 15 Pro & iPhone 15 Pro Max.jpg",
    "artist": "IPHONE 15",
    "licence": "CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:IPhone_15_Pro_%26_iPhone_15_Pro_Max.jpg"
  },
  {
    "slug": "iphone-15-pro-max",
    "name": "iPhone 15 Pro Max",
    "provider": "Wikimedia Commons",
    "title": "IPhone 15 Pro and Pro Max in Apple Store - 2.jpg",
    "artist": "Kyu3",
    "licence": "CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:IPhone_15_Pro_and_Pro_Max_in_Apple_Store_-_2.jpg"
  },
  {
    "slug": "iphone-16",
    "name": "iPhone 16",
    "provider": "Wikimedia Commons",
    "title": "About iPhone 16 Plus in Pink.jpg",
    "artist": "メイド理世",
    "licence": "CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:About_iPhone_16_Plus_in_Pink.jpg"
  },
  {
    "slug": "iphone-16-plus",
    "name": "iPhone 16 Plus",
    "provider": "Wikimedia Commons",
    "title": "About iPhone 16 Plus in Pink.jpg",
    "artist": "メイド理世",
    "licence": "CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:About_iPhone_16_Plus_in_Pink.jpg"
  },
  {
    "slug": "iphone-16-pro",
    "name": "iPhone 16 Pro",
    "provider": "Wikimedia Commons",
    "title": "About iPhone 16 Pro Max Natural Titanium.jpg",
    "artist": "メイド理世",
    "licence": "CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:About_iPhone_16_Pro_Max_Natural_Titanium.jpg"
  },
  {
    "slug": "iphone-16-pro-max",
    "name": "iPhone 16 Pro Max",
    "provider": "Wikimedia Commons",
    "title": "About iPhone 16 Pro Max Natural Titanium.jpg",
    "artist": "メイド理世",
    "licence": "CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:About_iPhone_16_Pro_Max_Natural_Titanium.jpg"
  },
  {
    "slug": "iphone-17",
    "name": "iPhone 17",
    "provider": "Wikimedia Commons",
    "title": "IPhone 17 launch at Apple TRX Malaysia 62.jpg",
    "artist": "Ahmad Ali Karim",
    "licence": "CC0",
    "source": "https://commons.wikimedia.org/wiki/File:IPhone_17_launch_at_Apple_TRX_Malaysia_62.jpg"
  },
  {
    "slug": "iphone-17-air",
    "name": "iPhone 17 Air",
    "provider": "Wikimedia Commons",
    "title": "IPhone XR and iPhone Air.jpg",
    "artist": "茅野ふたば",
    "licence": "CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:IPhone_XR_and_iPhone_Air.jpg"
  },
  {
    "slug": "iphone-17-pro",
    "name": "iPhone 17 Pro",
    "provider": "Wikimedia Commons",
    "title": "Silver iPhone 17 Pro Max.jpg",
    "artist": "Ahmad Ali Karim",
    "licence": "CC0",
    "source": "https://commons.wikimedia.org/wiki/File:Silver_iPhone_17_Pro_Max.jpg"
  },
  {
    "slug": "iphone-17-pro-max",
    "name": "iPhone 17 Pro Max",
    "provider": "Wikimedia Commons",
    "title": "IPhone 17 Pro Max.jpg",
    "artist": "茅野ふたば",
    "licence": "CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:IPhone_17_Pro_Max.jpg"
  },
  {
    "slug": "galaxy-s20",
    "name": "Galaxy S20",
    "provider": "Wikimedia Commons",
    "title": "Größenvergleich Samsung Galaxy S10 und S20 Ultra 5G.jpg",
    "artist": "PantheraLeo1359531",
    "licence": "CC BY 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Gr%C3%B6%C3%9Fenvergleich_Samsung_Galaxy_S10_und_S20_Ultra_5G.jpg"
  },
  {
    "slug": "galaxy-s20-plus",
    "name": "Galaxy S20 Plus",
    "provider": "Wikimedia Commons",
    "title": "Größenvergleich Samsung Galaxy S10 und S20 Ultra 5G.jpg",
    "artist": "PantheraLeo1359531",
    "licence": "CC BY 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Gr%C3%B6%C3%9Fenvergleich_Samsung_Galaxy_S10_und_S20_Ultra_5G.jpg"
  },
  {
    "slug": "galaxy-s20-ultra",
    "name": "Galaxy S20 Ultra",
    "provider": "Wikimedia Commons",
    "title": "Test Tapete Samsung Galaxy S20 Ultra 20200329 02.jpg",
    "artist": "PantheraLeo1359531",
    "licence": "CC BY 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Test_Tapete_Samsung_Galaxy_S20_Ultra_20200329_02.jpg"
  },
  {
    "slug": "galaxy-s21",
    "name": "Galaxy S21",
    "provider": "Wikimedia Commons",
    "title": "Samsung Galaxy S21 back.jpg",
    "artist": "X-SHLIED",
    "licence": "CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Samsung_Galaxy_S21_back.jpg"
  },
  {
    "slug": "galaxy-s21-ultra",
    "name": "Galaxy S21 Ultra",
    "provider": "Wikimedia Commons",
    "title": "SAMSUNG Galaxy S21 Ultra(1).jpg",
    "artist": "Dinkun Chen",
    "licence": "CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:SAMSUNG_Galaxy_S21_Ultra(1).jpg"
  },
  {
    "slug": "galaxy-s22",
    "name": "Galaxy S22",
    "provider": "Wikimedia Commons",
    "title": "SamsungGalaxyS22Series.png",
    "artist": "C4UNTRYB4LL193",
    "licence": "CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:SamsungGalaxyS22Series.png"
  },
  {
    "slug": "galaxy-s22-ultra",
    "name": "Galaxy S22 Ultra",
    "provider": "Wikimedia Commons",
    "title": "Back of the Samsung Galaxy S22 Ultra.jpg",
    "artist": "Hajoon0102",
    "licence": "CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Back_of_the_Samsung_Galaxy_S22_Ultra.jpg"
  },
  {
    "slug": "galaxy-s23",
    "name": "Galaxy S23",
    "provider": "Wikimedia Commons",
    "title": "Back of the Samsung Galaxy S23.jpg",
    "artist": "Hajoon0102",
    "licence": "CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Back_of_the_Samsung_Galaxy_S23.jpg"
  },
  {
    "slug": "galaxy-s23-ultra",
    "name": "Galaxy S23 Ultra",
    "provider": "Wikimedia Commons",
    "title": "Samsung Galaxy S23 Ultra, 512 GB, Lavender mit S-Pen 20230416 HOF00335 RAW-Export cens.png",
    "artist": "PantheraLeo1359531",
    "licence": "CC BY 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Samsung_Galaxy_S23_Ultra,_512_GB,_Lavender_mit_S-Pen_20230416_HOF00335_RAW-Export_cens.png"
  },
  {
    "slug": "galaxy-s24",
    "name": "Galaxy S24",
    "provider": "Wikimedia Commons",
    "title": "Samsung Galaxy S24 01.jpg",
    "artist": "Ganesh Mohan T",
    "licence": "CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Samsung_Galaxy_S24_01.jpg"
  },
  {
    "slug": "galaxy-s24-plus",
    "name": "Galaxy S24 Plus",
    "provider": "Wikimedia Commons",
    "title": "Samsung Galaxy S24+ 01.jpg",
    "artist": "Ganesh Mohan T",
    "licence": "CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Samsung_Galaxy_S24%2B_01.jpg"
  },
  {
    "slug": "galaxy-s24-ultra",
    "name": "Galaxy S24 Ultra",
    "provider": "Wikimedia Commons",
    "title": "Samsung Galaxy S24 Ultra Backside.jpg",
    "artist": "SimonWaldherr",
    "licence": "CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Samsung_Galaxy_S24_Ultra_Backside.jpg"
  },
  {
    "slug": "galaxy-s25",
    "name": "Galaxy S25",
    "provider": "Wikimedia Commons",
    "title": "Samsung Galaxy S25 Ultra Titanium Silverblue.jpg",
    "artist": "Alvis Jean",
    "licence": "CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Samsung_Galaxy_S25_Ultra_Titanium_Silverblue.jpg"
  },
  {
    "slug": "galaxy-s25-plus",
    "name": "Galaxy S25 Plus",
    "provider": "Wikimedia Commons",
    "title": "Samsung Galaxy S25+.jpg",
    "artist": "Jakub CA",
    "licence": "CC BY 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Samsung_Galaxy_S25%2B.jpg"
  },
  {
    "slug": "galaxy-s25-ultra",
    "name": "Galaxy S25 Ultra",
    "provider": "Wikimedia Commons",
    "title": "Samsung Galaxy S25 Ultra Titanium Silverblue.jpg",
    "artist": "Alvis Jean",
    "licence": "CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Samsung_Galaxy_S25_Ultra_Titanium_Silverblue.jpg"
  },
  {
    "slug": "galaxy-s26",
    "name": "Galaxy S26",
    "provider": "Wikimedia Commons",
    "title": "Galaxy S26 Ultra - 2.jpg",
    "artist": "Kyu3a",
    "licence": "CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Galaxy_S26_Ultra_-_2.jpg"
  },
  {
    "slug": "galaxy-s26-plus",
    "name": "Galaxy S26 Plus",
    "provider": "Wikimedia Commons",
    "title": "Galaxy S26 Ultra - 2.jpg",
    "artist": "Kyu3a",
    "licence": "CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Galaxy_S26_Ultra_-_2.jpg"
  },
  {
    "slug": "galaxy-s26-ultra",
    "name": "Galaxy S26 Ultra",
    "provider": "Wikimedia Commons",
    "title": "来了！第一手拿到Samsung S26全系列！这5件事一定要知道：最薄Ultra，60W快充、掰掰titanium！ (20260225)-00.03.57.461.png",
    "artist": "可恩Ke En",
    "licence": "CC BY 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:%E6%9D%A5%E4%BA%86%EF%BC%81%E7%AC%AC%E4%B8%80%E6%89%8B%E6%8B%BF%E5%88%B0Samsung_S26%E5%85%A8%E7%B3%BB%E5%88%97%EF%BC%81%E8%BF%995%E4%BB%B6%E4%BA%8B%E4%B8%80%E5%AE%9A%E8%A6%81%E7%9F%A5%E9%81%93%EF%BC%9A%E6%9C%80%E8%96%84Ultra%EF%BC%8C60W%E5%BF%AB%E5%85%85%E3%80%81%E6%8E%B0%E6%8E%B0titanium%EF%BC%81_(20260225)-00.03.57.461.png"
  },
  {
    "slug": "macbook-air-13-m4",
    "name": "MacBook Air 13\" M4",
    "provider": "Wikimedia Commons",
    "title": "MacBook Air (15-inch, M4, Silver).jpg",
    "artist": "AzureSaturn",
    "licence": "CC0",
    "source": "https://commons.wikimedia.org/wiki/File:MacBook_Air_(15-inch,_M4,_Silver).jpg"
  },
  {
    "slug": "macbook-air-15-m4",
    "name": "MacBook Air 15\" M4",
    "provider": "Wikimedia Commons",
    "title": "Macbook Air 15 inch - 1.jpg",
    "artist": "KKPCW（Kyu3）",
    "licence": "CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Macbook_Air_15_inch_-_1.jpg"
  },
  {
    "slug": "macbook-pro-14-m4-pro",
    "name": "MacBook Pro 14\" M4 Pro",
    "provider": "Wikimedia Commons",
    "title": "A 2021 14-inch Silver MacBook Pro (cropped).jpg",
    "artist": "Oops4321",
    "licence": "CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:A_2021_14-inch_Silver_MacBook_Pro_(cropped).jpg"
  },
  {
    "slug": "macbook-pro-16-m4-max",
    "name": "MacBook Pro 16\" M4 Max",
    "provider": "Wikimedia Commons",
    "title": "Teardown of MacBook Pro 16 inch laptop.jpg",
    "artist": "Netha Hussain",
    "licence": "CC0",
    "source": "https://commons.wikimedia.org/wiki/File:Teardown_of_MacBook_Pro_16_inch_laptop.jpg"
  },
  {
    "slug": "dell-xps-13",
    "name": "Dell XPS 13",
    "provider": "Wikimedia Commons",
    "title": "DELL XPS 13 and 15 (37041682184).jpg",
    "artist": "Tinh tế Photo",
    "licence": "CC0",
    "source": "https://commons.wikimedia.org/wiki/File:DELL_XPS_13_and_15_(37041682184).jpg"
  },
  {
    "slug": "dell-xps-15",
    "name": "Dell XPS 15",
    "provider": "Wikimedia Commons",
    "title": "DELL XPS 13 and 15 (37080596413).jpg",
    "artist": "Tinh tế Photo",
    "licence": "CC0",
    "source": "https://commons.wikimedia.org/wiki/File:DELL_XPS_13_and_15_(37080596413).jpg"
  },
  {
    "slug": "dell-inspiron-15",
    "name": "Dell Inspiron 15",
    "provider": "Wikimedia Commons",
    "title": "Dell Inspiron 15 7000 (7559) (1).jpg",
    "artist": "NOAA National Severe Storms Laboratory",
    "licence": "Public domain",
    "source": "https://commons.wikimedia.org/wiki/File:Dell_Inspiron_15_7000_(7559)_(1).jpg"
  },
  {
    "slug": "dell-latitude-5450",
    "name": "Dell Latitude 5450",
    "provider": "Wikimedia Commons",
    "title": "Dell Latitude with Ubuntu.jpg",
    "artist": "No machine-readable author provided. MarkGallagher~commonswiki assumed (based on copyright claims).",
    "licence": "CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Dell_Latitude_with_Ubuntu.jpg"
  },
  {
    "slug": "hp-spectre-x360-14",
    "name": "HP Spectre x360 14",
    "provider": "Wikimedia Commons",
    "title": "Hp Spectre x360.jpg",
    "artist": "Lokeish",
    "licence": "CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Hp_Spectre_x360.jpg"
  },
  {
    "slug": "hp-pavilion-15",
    "name": "HP Pavilion 15",
    "provider": "Wikimedia Commons",
    "title": "HP Pavilion dv6000 laptop.jpg",
    "artist": "Shleiderbmx",
    "licence": "CC BY 3.0",
    "source": "https://commons.wikimedia.org/wiki/File:HP_Pavilion_dv6000_laptop.jpg"
  },
  {
    "slug": "hp-elitebook-840-g11",
    "name": "HP EliteBook 840 G11",
    "provider": "Wikimedia Commons",
    "title": "HP Elitebook 8770w.png",
    "artist": "0x0077BE",
    "licence": "CC0",
    "source": "https://commons.wikimedia.org/wiki/File:HP_Elitebook_8770w.png"
  },
  {
    "slug": "hp-omen-16",
    "name": "HP Omen 16",
    "provider": "Wikimedia Commons",
    "title": "My Omen - keyboard.jpg",
    "artist": "Castio T. Lauren",
    "licence": "CC BY-SA 2.0",
    "source": "https://commons.wikimedia.org/wiki/File:My_Omen_-_keyboard.jpg"
  },
  {
    "slug": "lenovo-thinkpad-x1-carbon",
    "name": "Lenovo ThinkPad X1 Carbon",
    "provider": "Wikimedia Commons",
    "title": "Thinkpad X1 Carbon.jpg",
    "artist": "Mariofan13",
    "licence": "CC BY-SA 3.0",
    "source": "https://commons.wikimedia.org/wiki/File:Thinkpad_X1_Carbon.jpg"
  },
  {
    "slug": "lenovo-ideapad-slim-3",
    "name": "Lenovo IdeaPad Slim 3",
    "provider": "Wikimedia Commons",
    "title": "Lenovo IdeaPad Yoga 13 (1).jpg",
    "artist": "Great Brightstar",
    "licence": "CC BY-SA 3.0",
    "source": "https://commons.wikimedia.org/wiki/File:Lenovo_IdeaPad_Yoga_13_(1).jpg"
  },
  {
    "slug": "lenovo-legion-5",
    "name": "Lenovo Legion 5",
    "provider": "Wikimedia Commons",
    "title": "Lenovo Legion Y520 (1).jpg",
    "artist": "TAKA@P.P.R.S",
    "licence": "CC BY-SA 2.0",
    "source": "https://commons.wikimedia.org/wiki/File:Lenovo_Legion_Y520_(1).jpg"
  },
  {
    "slug": "asus-rog-zephyrus-g14",
    "name": "ASUS ROG Zephyrus G14",
    "provider": "Wikimedia Commons",
    "title": "Tokyo-Game-Show-2025 0121.jpg",
    "artist": "RuinDig/Yuki Uchida",
    "licence": "CC BY 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Tokyo-Game-Show-2025_0121.jpg"
  },
  {
    "slug": "asus-vivobook-15",
    "name": "ASUS Vivobook 15",
    "provider": "Wikimedia Commons",
    "title": "Asus vivobook pro 15 N580vd.jpg",
    "artist": "Saisumanth532",
    "licence": "CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Asus_vivobook_pro_15_N580vd.jpg"
  },
  {
    "slug": "ipad-11th-gen",
    "name": "iPad (11th gen)",
    "provider": "Wikimedia Commons",
    "title": "IPad 10th Generation 2024.jpg",
    "artist": "Captainmorlypogi1959",
    "licence": "CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:IPad_10th_Generation_2024.jpg"
  },
  {
    "slug": "ipad-air-13-m3",
    "name": "iPad Air 13\" M3",
    "provider": "Wikimedia Commons",
    "title": "M2 iPad Air 13inti.jpg",
    "artist": "Kyu3a",
    "licence": "CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:M2_iPad_Air_13inti.jpg"
  },
  {
    "slug": "ipad-pro-13-m4",
    "name": "iPad Pro 13\" M4",
    "provider": "Wikimedia Commons",
    "title": "M4 iPad Pro back camera.jpg",
    "artist": "Kyu3a",
    "licence": "CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:M4_iPad_Pro_back_camera.jpg"
  },
  {
    "slug": "galaxy-tab-s10-fe",
    "name": "Galaxy Tab S10 FE",
    "provider": "Wikimedia Commons",
    "title": "Samsung Galaxy Tab S9.png",
    "artist": "AnVuong1222004 (11)",
    "licence": "CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Samsung_Galaxy_Tab_S9.png"
  },
  {
    "slug": "galaxy-tab-s11-ultra",
    "name": "Galaxy Tab S11 Ultra",
    "provider": "Wikimedia Commons",
    "title": "20230729 삼성 갤럭시 탭 S9.jpg",
    "artist": "Striker9498",
    "licence": "CC BY-SA 3.0",
    "source": "https://commons.wikimedia.org/wiki/File:20230729_%EC%82%BC%EC%84%B1_%EA%B0%A4%EB%9F%AD%EC%8B%9C_%ED%83%AD_S9.jpg"
  },
  {
    "slug": "20w-usb-c-power-adapter",
    "name": "20W USB-C Power Adapter",
    "provider": "Wikimedia Commons",
    "title": "Apple USB-C (USB Type C) 87W Power Adapter for MacBook Pro (48979218053).jpg",
    "artist": "Tony Webster from Minneapolis, Minnesota, United States",
    "licence": "CC BY-SA 2.0",
    "source": "https://commons.wikimedia.org/wiki/File:Apple_USB-C_(USB_Type_C)_87W_Power_Adapter_for_MacBook_Pro_(48979218053).jpg"
  },
  {
    "slug": "magsafe-charger",
    "name": "MagSafe Charger",
    "provider": "Wikimedia Commons",
    "title": "Apple iBook puck and brick chargers before MagSafe.jpg",
    "artist": "DMahalko, Dale Mahalko, Gilman, WI, USA -- Email: dmahalko@gmail.com",
    "licence": "CC BY-SA 3.0",
    "source": "https://commons.wikimedia.org/wiki/File:Apple_iBook_puck_and_brick_chargers_before_MagSafe.jpg"
  },
  {
    "slug": "65w-gan-charger",
    "name": "65W GaN Charger",
    "provider": "Wikimedia Commons",
    "title": "Lazos GaN Charger 30W L-AC-G30.jpg",
    "artist": "Qurren",
    "licence": "CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Lazos_GaN_Charger_30W_L-AC-G30.jpg"
  },
  {
    "slug": "20000mah-power-bank",
    "name": "20,000mAh Power Bank",
    "provider": "Wikimedia Commons",
    "title": "Turbo Akku Vac Easy Home VC 618WP - battery pack-1376.jpg",
    "artist": "Raimond Spekking",
    "licence": "CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Turbo_Akku_Vac_Easy_Home_VC_618WP_-_battery_pack-1376.jpg"
  },
  {
    "slug": "usb-c-to-usb-c-cable-2m",
    "name": "USB-C to USB-C Cable (2m)",
    "provider": "Wikimedia Commons",
    "title": "USB-C cable 2017 A.jpg",
    "artist": "Fructibus",
    "licence": "CC0",
    "source": "https://commons.wikimedia.org/wiki/File:USB-C_cable_2017_A.jpg"
  },
  {
    "slug": "clear-magsafe-case",
    "name": "Clear MagSafe Case",
    "provider": "Wikimedia Commons",
    "title": "Mobile phone cage in high school.jpg",
    "artist": "Chainwit.",
    "licence": "CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Mobile_phone_cage_in_high_school.jpg"
  },
  {
    "slug": "airpods-4-anc",
    "name": "AirPods 4 (ANC)",
    "provider": "Wikimedia Commons",
    "title": "AirPods (cropped).jpg",
    "artist": "Maurizio Pesce from Milan, Italia",
    "licence": "CC BY 2.0",
    "source": "https://commons.wikimedia.org/wiki/File:AirPods_(cropped).jpg"
  },
  {
    "slug": "airpods-pro-3",
    "name": "AirPods Pro 3",
    "provider": "Wikimedia Commons",
    "title": "AirPods Pro case.jpg",
    "artist": "— aconcagua (talk)",
    "licence": "CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:AirPods_Pro_case.jpg"
  },
  {
    "slug": "airpods-max",
    "name": "AirPods Max",
    "provider": "Wikimedia Commons",
    "title": "Apple airpods max 1.jpg",
    "artist": "Arne Müseler",
    "licence": "CC BY-SA 3.0 de",
    "source": "https://commons.wikimedia.org/wiki/File:Apple_airpods_max_1.jpg"
  },
  {
    "slug": "galaxy-buds3-pro",
    "name": "Galaxy Buds3 Pro",
    "provider": "Wikimedia Commons",
    "title": "SAMSUNG Galaxy Buds+ (2).jpg",
    "artist": "Dinkun Chen",
    "licence": "CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:SAMSUNG_Galaxy_Buds%2B_(2).jpg"
  },
  {
    "slug": "sony-wh-1000xm6",
    "name": "Sony WH-1000XM6",
    "provider": "Wikimedia Commons",
    "title": "Bose QuietComfort 25 Acoustic Noise Cancelling Headphones.jpg",
    "artist": "Florian Fuchs",
    "licence": "CC BY-SA 3.0",
    "source": "https://commons.wikimedia.org/wiki/File:Bose_QuietComfort_25_Acoustic_Noise_Cancelling_Headphones.jpg"
  },
  {
    "slug": "apple-watch-series-10",
    "name": "Apple Watch Series 10",
    "provider": "Wikimedia Commons",
    "title": "Apple Watch Series 9 1 2023-11-14.jpg",
    "artist": "FASTILY",
    "licence": "CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Apple_Watch_Series_9_1_2023-11-14.jpg"
  },
  {
    "slug": "apple-watch-ultra-2",
    "name": "Apple Watch Ultra 2",
    "provider": "Wikimedia Commons",
    "title": "Apple Watch Ultra - 3.jpg",
    "artist": "KKPCW（Kyu3）",
    "licence": "CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Apple_Watch_Ultra_-_3.jpg"
  },
  {
    "slug": "galaxy-watch-7",
    "name": "Galaxy Watch 7",
    "provider": "Wikimedia Commons",
    "title": "SAMSUNG Galaxy Watch (2).jpg",
    "artist": "Dinkun Chen",
    "licence": "CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:SAMSUNG_Galaxy_Watch_(2).jpg"
  },
  {
    "slug": "playstation-5-slim",
    "name": "PlayStation 5 Slim",
    "provider": "Wikimedia Commons",
    "title": "Immagine Playstation 5.jpg",
    "artist": "Gianlupisa1",
    "licence": "CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Immagine_Playstation_5.jpg"
  },
  {
    "slug": "playstation-5-pro",
    "name": "PlayStation 5 Pro",
    "provider": "Wikimedia Commons",
    "title": "PlayStation 5 Pro no disc drive.jpg",
    "artist": "BeatEmUps",
    "licence": "CC BY 3.0",
    "source": "https://commons.wikimedia.org/wiki/File:PlayStation_5_Pro_no_disc_drive.jpg"
  },
  {
    "slug": "xbox-series-x",
    "name": "Xbox Series X",
    "provider": "Wikimedia Commons",
    "title": "Xbox series X (50648118708).jpg",
    "artist": "Ian Hughes",
    "licence": "CC BY 2.0",
    "source": "https://commons.wikimedia.org/wiki/File:Xbox_series_X_(50648118708).jpg"
  },
  {
    "slug": "xbox-series-s",
    "name": "Xbox Series S",
    "provider": "Wikimedia Commons",
    "title": "Xbox Series X.png",
    "artist": "Emrekozan00",
    "licence": "CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Xbox_Series_X.png"
  },
  {
    "slug": "dualsense-wireless-controller",
    "name": "DualSense Wireless Controller",
    "provider": "Wikimedia Commons",
    "title": "Playstation Dualsense controller.jpg",
    "artist": "Sergey Galyonkin",
    "licence": "CC BY-SA 2.0",
    "source": "https://commons.wikimedia.org/wiki/File:Playstation_Dualsense_controller.jpg"
  },
  {
    "slug": "nintendo-switch-2",
    "name": "Nintendo Switch 2",
    "provider": "Wikimedia Commons",
    "title": "Nintendo Switch 2 Joy-Con 2 Blue and Orange.jpg",
    "artist": "Crisco 1492",
    "licence": "CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Nintendo_Switch_2_Joy-Con_2_Blue_and_Orange.jpg"
  },
  {
    "slug": "pro-gaming-headset-7-1",
    "name": "Pro Gaming Headset 7.1",
    "provider": "Wikimedia Commons",
    "title": "Gaming computer with bat decals.jpg",
    "artist": "JD Hancock",
    "licence": "CC BY 2.0",
    "source": "https://commons.wikimedia.org/wiki/File:Gaming_computer_with_bat_decals.jpg"
  },
  {
    "slug": "27-qhd-165hz-gaming-monitor",
    "name": "27\" QHD 165Hz Gaming Monitor",
    "provider": "Wikimedia Commons",
    "title": "Computer monitor screen image simulated.jpg",
    "artist": "Unknown",
    "licence": "CC BY-SA 3.0",
    "source": "https://commons.wikimedia.org/wiki/File:Computer_monitor_screen_image_simulated.jpg"
  },
  {
    "slug": "quantum-hybrid-inverter-3-5kva",
    "name": "Quantum Hybrid Inverter 3.5kVA",
    "provider": "Wikimedia Commons",
    "title": "Tesla Solar Inverter and AC disconnect.jpg",
    "artist": "RickyCourtney",
    "licence": "CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Tesla_Solar_Inverter_and_AC_disconnect.jpg"
  },
  {
    "slug": "quantum-hybrid-inverter-5kva",
    "name": "Quantum Hybrid Inverter 5kVA",
    "provider": "Wikimedia Commons",
    "title": "Tesla Solar Inverter and AC disconnect.jpg",
    "artist": "RickyCourtney",
    "licence": "CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Tesla_Solar_Inverter_and_AC_disconnect.jpg"
  },
  {
    "slug": "quantum-hybrid-inverter-10kva",
    "name": "Quantum Hybrid Inverter 10kVA",
    "provider": "Wikimedia Commons",
    "title": "GE-Carport.jpg",
    "artist": "Mauricio.anon",
    "licence": "CC BY-SA 3.0",
    "source": "https://commons.wikimedia.org/wiki/File:GE-Carport.jpg"
  },
  {
    "slug": "550w-monocrystalline-panel",
    "name": "550W Monocrystalline Panel",
    "provider": "Wikimedia Commons",
    "title": "Solar Panel Covered Conapy for Cambridge University's Solar Race Car.jpg",
    "artist": "Intel Free Press",
    "licence": "CC BY-SA 2.0",
    "source": "https://commons.wikimedia.org/wiki/File:Solar_Panel_Covered_Conapy_for_Cambridge_University%27s_Solar_Race_Car.jpg"
  },
  {
    "slug": "220ah-lithium-battery-lifepo4",
    "name": "220Ah Lithium Battery (LiFePO4)",
    "provider": "Wikimedia Commons",
    "title": "Lithium Iron Phosphate LiFePO4 Cells 700 Ah Amp Hours 3.25 Volts - 7.jpg",
    "artist": "Yo-Co-Man",
    "licence": "CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Lithium_Iron_Phosphate_LiFePO4_Cells_700_Ah_Amp_Hours_3.25_Volts_-_7.jpg"
  },
  {
    "slug": "6-6kw-rooftop-solar-array",
    "name": "6.6kW Rooftop Solar Array",
    "provider": "Wikimedia Commons",
    "title": "Farooq Abdullah addressing at the launch of the guidelines for two schemes (i) off-grid (photovoltaic & thermal) and decentralized solar applications and (ii) Rooftop & other small solar power plants.jpg",
    "artist": "Ministry of New and Renewable Energy, Government of India",
    "licence": "GODL-India",
    "source": "https://commons.wikimedia.org/wiki/File:Farooq_Abdullah_addressing_at_the_launch_of_the_guidelines_for_two_schemes_(i)_off-grid_(photovoltaic_%26_thermal)_and_decentralized_solar_applications_and_(ii)_Rooftop_%26_other_small_solar_power_plants.jpg"
  },
  {
    "slug": "home-backup-bundle-5kva",
    "name": "Home Backup Bundle 5kVA",
    "provider": "Wikimedia Commons",
    "title": "BACKYARD SOLAR HEATING SYSTEM BEING INSTALLED AT A HOME THE SYSTEM WAS DEVELOPED BY INTERNATIONAL SOLARTHERMICS... - NARA - 557334.jpg",
    "artist": "Boyd Norton",
    "licence": "Public domain",
    "source": "https://commons.wikimedia.org/wiki/File:BACKYARD_SOLAR_HEATING_SYSTEM_BEING_INSTALLED_AT_A_HOME_THE_SYSTEM_WAS_DEVELOPED_BY_INTERNATIONAL_SOLARTHERMICS..._-_NARA_-_557334.jpg"
  },
  {
    "slug": "category-phones",
    "name": "phones category",
    "provider": "Wikimedia Commons",
    "title": "5 different Smartphones.jpg",
    "artist": "Kskhh",
    "licence": "CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:5_different_Smartphones.jpg"
  },
  {
    "slug": "category-laptops",
    "name": "laptops category",
    "provider": "Wikimedia Commons",
    "title": "2006 broken laptop computer 237398638.jpg",
    "artist": "Bruce Turner from AustinTX",
    "licence": "CC BY 2.0",
    "source": "https://commons.wikimedia.org/wiki/File:2006_broken_laptop_computer_237398638.jpg"
  },
  {
    "slug": "category-tablets",
    "name": "tablets category",
    "provider": "Wikimedia Commons",
    "title": "Kids with Education Tablet Computers.jpg",
    "artist": "Intel Free Press",
    "licence": "CC BY-SA 2.0",
    "source": "https://commons.wikimedia.org/wiki/File:Kids_with_Education_Tablet_Computers.jpg"
  },
  {
    "slug": "category-audio",
    "name": "audio category",
    "provider": "Wikimedia Commons",
    "title": "Headphones 1.jpg",
    "artist": "No machine-readable author provided. PJ assumed (based on copyright claims).",
    "licence": "CC BY-SA 3.0",
    "source": "https://commons.wikimedia.org/wiki/File:Headphones_1.jpg"
  },
  {
    "slug": "category-gaming",
    "name": "gaming category",
    "provider": "Wikimedia Commons",
    "title": "Game-Boy-Original.jpg",
    "artist": "Evan-Amos",
    "licence": "Public domain",
    "source": "https://commons.wikimedia.org/wiki/File:Game-Boy-Original.jpg"
  },
  {
    "slug": "category-solar",
    "name": "solar category",
    "provider": "Wikimedia Commons",
    "title": "Ground mounted solar panels.gk.jpg",
    "artist": "Grendelkhan",
    "licence": "CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Ground_mounted_solar_panels.gk.jpg"
  }
];
